CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE UserDatabases (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    dbName VARCHAR(255) NOT NULL,
    dbType ENUM('mysql', 'postgres', 'mssql') NOT NULL,
    dbHost VARCHAR(255) NOT NULL,
    dbUser VARCHAR(255) NOT NULL,
    dbPassword VARCHAR(255) NOT NULL,
    dbDatabase VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);
